### ISSUE TITLE
Does panflute need to be installed separately?

### ISSUE THREAD

**Issue by amundo** [daemanos/pangloss#7]
Getting this when I try running pangloss:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/pangloss", line 5, in <module>
    from pangloss.pangloss import main
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pangloss/pangloss.py", line 3, in <module>
    import panflute as pf
ModuleNotFoundError: No module named 'panflute'
Error running filter pangloss:
Filter returned error status 1
```

thanks

**Comment by CLRafaelR** [comment]
@amundo 

You need to just install [`panflute` module](https://github.com/sergiocorreia/panflute) via pip:

```
pip install panflute
```
